#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=2
#PBS -N 2dplot
#PBS -A d411-training
#PBS -j oe

### script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/bioc0023/
cd ~/output/bioc0023/

# QIIME 

make_2d_plots.py -i ./cdout2/bdiv_even30000/weighted_unifrac_pc.txt -m ./anosim_mf.tsv -b 'Time' -o 2d_plots/

echo "closing environment"

conda deactivate

#end script
