#!/bin/bash --login
#PBS -l walltime=30:00:00
#PBS -l select=1:ncpus=2
#PBS -N distanceplot
#PBS -A d411-training
#PBS -j oe

### script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/bioc0023/
cd ~/output/bioc0023/

# QIIME Code

make_distance_comparison_plots.py -d ./cdout2/bdiv_even30000/weighted_unifrac_dm.txt -m anosim_mf.tsv -f Time -c "Before,ImmediateWash,ThirtyMinutes,TwoHours" -o out1

echo "closing environment"
conda deactivate
~                           
