#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=8
#PBS -N heatmap4
#PBS -A d411-training
#PBS -j oe

# script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/
cd ~/output/

# QIIME Code
 

make_otu_heatmap.py -i ./new_otu_table_L2.biom -o heatmap4.pdf -m ./bioc0023/anosim_mf.tsv -c Time --color_scheme BuPa 

echo "closing environment"
conda deactivate

# end script
