#!/bin/bash --login
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=8
#PBS -N plot_taxa_summary
#PBS -A d411-training
#PBS -j oe

### script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/bioc0023/
cd ~/output/bioc0023/

# QIIME Code

plot_taxa_summary.py -i ./otus_2/tax2/otu_table_L2.txt -l phylum -c pie,bar,area -o phylum_charts/

echo "closing environment"
conda deactivate
