#!/bin/bash --login
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=8
#PBS -N compare_categories2
#PBS -A d411-training
#PBS -j oe

### script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/bioc0023/
cd ~/output/bioc0023/

# QIIME Code

compare_categories.py --method adonis -i ./cdout2/bdiv_even30000/weighted_unifrac_dm.txt -m./anosim_mf.tsv  -c Time  -o adonis_weighted2 -n 999

compare_categories.py --method anosim -i ./cdout2/bdiv_even30000/weighted_unifrac_dm.txt -m ./anosim_mf.tsv -c Time -o anosim_weighted2  -n 99

echo "closing environment"
conda deactivate
