#!/bin/bash --login
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=1
#PBS -N group_significance2
#PBS -A d411-training
#PBS -j oe

### script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/bioc0023/
cd ~/output/bioc0023/

# QIIME Code

group_significance.py  -i ./otus_2/otu_table.biom  -m ./anosim_mf.tsv -c Time  -s g_test -o gtest.txt

echo "closing environment"

conda deactivate
