#!/bin/bash --login
# reduce the walltime as more cores are requested
#PBS -l walltime=02:00:00
# to request more cores change ncpus
#PBS -l select=1:ncpus=8
#PBS -N otu_picking2
#PBS -A d411-training
#PBS -j oe

### script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/bioc0023/
cd ~/output/bioc0023/

# QIIME code

echo "8 core"
echo "Picking closed reference OTUs"
echo "Full dataset"
for i in {1..3}
do
    echo "run $i"
    time pick_closed_reference_otus.py \
    -i ./round2/slout2/seqs.fna \
    -o otus_2 \
    -f -a -O 8
done

echo "closing environment"
conda deactivate

### end script
