#!/bin/bash --login
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=1
#PBS -N sharedphylotypes
#PBS -A d411-training
#PBS -j oe

### script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/bioc0023/
cd ~/output/bioc0023/

# QIIME 

shared_phylotypes.py -i ./otus_2/tax2/otu_table_L2.biom -o shared_otus.txt

echo "closing environment"

conda deactivate
